name: lustrous_lux
description: A high-end, premium mobile application for wealth and luxury lifestyle.
publish_to: 'none'
version: 1.3.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Backend (Updated for compatibility)
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.5.0

  # State Management & Architecture
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.7.0

  dartz: ^0.10.1
  flutter_animate: ^4.5.0
  local_auth: ^2.1.8
  sensors_plus: ^5.0.0

  # UI & Media
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  flutter_pdfview: ^1.3.2 # Mobile only
  url_launcher: ^6.3.0 # Fallback for Web
  http: ^1.2.1
  
  # Utils
  intl: ^0.20.2
  package_info_plus: ^8.0.0
  shared_preferences: ^2.5.1
  permission_handler: ^11.3.0
  share_plus: ^12.0.1
  syncfusion_flutter_pdfviewer: ^32.1.22
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
